version: '3.1'
services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks: 
      infra:
        ipv4_address: 172.18.0.10
    ports:
      - ${API_PORT}:8080
    environment:
      DB_HOST: db
      DB_PORT: ${POSTGRES_DB_PORT}
      DB_NAME: ${POSTGRES_DB_NAME}
      DB_USER: ${POSTGRES_DB_USER}
      DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
    
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    networks: 
      infra:
        ipv4_address: 172.18.0.11
    ports:
      - ${POSTGRES_DB_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    volumes:
      - ./postgres/sql:/docker-entrypoint-initdb.d
      - data_pg_movie:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks: 
      infra:
        ipv4_address: 172.18.0.13
    ports:
      - ${FRONT_PORT}:80
    volumes:
      - jenkins_repositories:/usr/local/apache2/htdocs:ro


volumes:
  data_pg_movie:
  jenkins_repositories:
    external:
      name: repos_front
networks:
  infra:
    external: true

