version: '3.1'
services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      infra:
        ipv4_address: 172.18.0.10
    ports:
      - ${API_PORT}:8080
    environment:
      DB_HOST: db
    

  db:
    build:
      context: ./oracle
      dockerfile: Dockerfile
    networks:
      infra:
        ipv4_address: 172.18.0.20
    ports:
      - ${ORACLE_DB_PORT}:1521
      - ${ORACLE_ADMIN_PORT}:5500
    environment:
      - ORACLE_PWD=${ORACLE_PASSWORD}
      - ENABLE_ARCHIVELOG=TRUE
    volumes:
      - oradata:/opt/oracle/oradata
      - orabackup:/opt/oracle/backup
      - ./oracle/scripts:/docker-entrypoint-initdb.d/setup

  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    networks:
      infra:
        ipv4_address: 172.18.0.13
    ports:
      - ${FRONT_PORT}:80
    volumes:
      - jenkins_repositories:/usr/local/apache2/htdocs

volumes:
  oradata:
  orabackup:
  jenkins_repositories:
    external:
      name: repos_front
networks:
  infra:
    external: true
